# Generated by Django 4.0.3 on 2022-06-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumenty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muzyk',
            name='opis',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='muzyk',
            field=models.ManyToManyField(to='instrumenty.muzyk'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='rodzaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumenty.rodzaj'),
        ),
    ]
