# Generated by Django 4.0.3 on 2022-06-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumenty', '0002_muzyk_opis_alter_instrument_muzyk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muzyk',
            name='opis',
        ),
    ]
