# Generated by Django 4.0.3 on 2022-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumenty', '0004_rename_instrument_instruments_rename_muzyk_muzycy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muzycy',
            name='opis',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
